# Generated by Django 3.1.3 on 2021-04-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('accountNum', models.IntegerField(primary_key=True, serialize=False)),
                ('totalNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('payment_time', models.DateTimeField()),
                ('accountNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobe.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobe.member'),
        ),
    ]
